name = "tc-study"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Production environment
[env.production]
name = "tc-study"

# Preview deployments
[env.preview]
name = "tc-study-preview"
